version: "3.8"
services:
  lidar_obstacle_detection:
    image: pang/lidar_obstacle_detection:1
    container_name: lidar_obstacle_detection
    network_mode: host
    # networks:
    #   - network1
    environment:
      - DISPLAY=$DISPLAY
    tty: true
    stdin_open: true
    command: ros2 launch lidar_obstacle_detection environment.launch.py use_rviz:=true env_config:=config/environment.yaml
    privileged: true
    volumes:
      # - ../data:/root/colcon_ws/src/lidar_obstacle_detection/data
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - "../config:/root/colcon_ws/install/lidar_obstacle_detection/share/lidar_obstacle_detection/config"

# networks:
#   network1:
#       name: network1
#       external: false